# Generated by Django 3.0 on 2022-07-19 11:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('dd', models.CharField(max_length=150)),
                ('vn', models.CharField(max_length=150)),
                ('ep', models.BigIntegerField()),
                ('dt', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
