# Generated by Django 3.0 on 2022-07-16 09:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='dt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.IntegerField()),
                ('hm', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('wd', models.IntegerField()),
                ('ws', models.IntegerField()),
                ('sm', models.IntegerField()),
                ('st', models.IntegerField()),
                ('sc', models.IntegerField()),
                ('lt', models.IntegerField()),
                ('lw', models.IntegerField()),
                ('bl', models.IntegerField()),
                ('pv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd', models.CharField(max_length=150)),
                ('vn', models.CharField(max_length=150)),
                ('ep', models.CharField(max_length=150)),
                ('dt', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
