# Generated by Django 3.0 on 2022-07-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dt',
        ),
    ]
