# Generated by Django 3.2.12 on 2022-08-26 13:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('dd', models.CharField(max_length=150)),
                ('vn', models.CharField(max_length=150)),
                ('ep', models.BigIntegerField()),
                ('dt', djongo.models.fields.JSONField()),
            ],
        ),
    ]
